### ISSUE TITLE
Add eigenvector centrality function

### ISSUE THREAD

**Issue by jhollway** [jhollway/migraph#31]
**[Original report](https://bitbucket.org/jhollway/roctopus/issue/31) by James Hollway (Bitbucket: [jhollway](https://bitbucket.org/jhollway), GitHub: [jhollway](https://github.com/jhollway)).**

----------------------------------------

**Comment by henriquesposito** [comment]
I am having a bit of trouble finding a consistent, as well as, translating the mathematical equations for eigenvector in two-mode networks. There are several mentions of it across the literature (Borgatti and Everett 1997; Borgatti and Halgin 2011; Faust 1997; among others). I think Faust (1997) is presents the better discussion for eigenvector for two-mode. I will keep on working and trying, just an update on where I am and why this is taking so long to finish.
