### ISSUE TITLE
Add centralization functions

### ISSUE THREAD

**Issue by jhollway** [jhollway/migraph#32]
**[Original report](https://bitbucket.org/jhollway/roctopus/issue/32) by James Hollway (Bitbucket: [jhollway](https://bitbucket.org/jhollway), GitHub: [jhollway](https://github.com/jhollway)).**

----------------------------------------

**Comment by henriquesposito** [comment]
Some centralization functions were added but can be improved to display centralization scores for different modes of a network. Eigenvector is missing but will be added once eigenvector centrality is done.

**Comment by henriquesposito** [comment]
I am currently adding the missing options for some of the centralization functions as well as wrappers around the different {igraph} centralization functions to calculate one-mode centralization.
